const OPORTUNIDADES = [
    {
        id: 'HA-42368',
        marca: 'Dodge',
        modelo: 'Charger SXT',
        anio: 2022,
        tipo: 'sedan',
        origen: 'mexico',
        precioMercado: 620000,
        precioTotal: 236250,
        ahorroMXN: 383750,
        danio: 'Recuperado / Por revisar',
        notas: 'Querétaro',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-42369',
        marca: 'Dodge',
        modelo: 'Charger SXT',
        anio: 2022,
        tipo: 'sedan',
        origen: 'mexico',
        precioMercado: 620000,
        precioTotal: 236250,
        ahorroMXN: 383750,
        danio: 'Recuperado / Por revisar',
        notas: 'Querétaro',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-41703',
        marca: 'Nissan',
        modelo: 'NP300',
        anio: 2013,
        tipo: 'pickup',
        origen: 'mexico',
        precioMercado: 190000,
        precioTotal: 67500,
        ahorroMXN: 122500,
        danio: 'Desgaste de uso',
        notas: 'Sinaloa',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-41704',
        marca: 'Ram',
        modelo: '1500',
        anio: 2019,
        tipo: 'pickup',
        origen: 'mexico',
        precioMercado: 450000,
        precioTotal: 163350,
        ahorroMXN: 286650,
        danio: 'Por evaluar',
        notas: 'Estado de México',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-41705',
        marca: 'Ford',
        modelo: 'Transit 115 T300',
        anio: 2011,
        tipo: 'suv',
        origen: 'mexico',
        precioMercado: 210000,
        precioTotal: 78300,
        ahorroMXN: 131700,
        danio: 'Uso rudo',
        notas: 'Guanajuato',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-42548',
        marca: 'Freightliner',
        modelo: 'M2',
        anio: 2013,
        tipo: 'pickup',
        origen: 'mexico',
        precioMercado: 650000,
        precioTotal: 337500,
        ahorroMXN: 312500,
        danio: 'Operativo',
        notas: 'Querétaro',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-41706',
        marca: 'Isuzu',
        modelo: 'Elf 300',
        anio: 2010,
        tipo: 'pickup',
        origen: 'mexico',
        precioMercado: 180000,
        precioTotal: 60750,
        ahorroMXN: 119250,
        danio: 'Desgaste',
        notas: 'Baja California Sur',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-41707',
        marca: 'Isuzu',
        modelo: 'Elf 400',
        anio: 2010,
        tipo: 'pickup',
        origen: 'mexico',
        precioMercado: 190000,
        precioTotal: 40500,
        ahorroMXN: 149500,
        danio: 'Avería mecánica',
        notas: 'Estado De Mexico',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-41709',
        marca: 'Isuzu',
        modelo: 'Elf 400',
        anio: 2008,
        tipo: 'pickup',
        origen: 'mexico',
        precioMercado: 160000,
        precioTotal: 27000,
        ahorroMXN: 133000,
        danio: 'Baja',
        notas: 'Quintana Roo',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-42549',
        marca: 'Kenworth',
        modelo: 'T370 6X4',
        anio: 2011,
        tipo: 'pickup',
        origen: 'mexico',
        precioMercado: 550000,
        precioTotal: 270000,
        ahorroMXN: 280000,
        danio: 'Recuperado',
        notas: 'CDMX',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-41710',
        marca: 'Kenworth',
        modelo: 'T370 6X4',
        anio: 2010,
        tipo: 'pickup',
        origen: 'mexico',
        precioMercado: 520000,
        precioTotal: 243000,
        ahorroMXN: 277000,
        danio: 'Recuperado',
        notas: 'Yucatán',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-42646',
        marca: 'Freightliner',
        modelo: 'M2',
        anio: 2012,
        tipo: 'pickup',
        origen: 'mexico',
        precioMercado: 600000,
        precioTotal: 297000,
        ahorroMXN: 303000,
        danio: 'Recuperado',
        notas: 'Monterrey',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-42554',
        marca: 'Kenworth',
        modelo: 'Tractocamión',
        anio: 2011,
        tipo: 'pickup',
        origen: 'mexico',
        precioMercado: 450000,
        precioTotal: 162000,
        ahorroMXN: 288000,
        danio: 'Para revivir',
        notas: 'Puebla',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-41712',
        marca: 'Hino',
        modelo: '514',
        anio: 2012,
        tipo: 'pickup',
        origen: 'mexico',
        precioMercado: 210000,
        precioTotal: 67500,
        ahorroMXN: 142500,
        danio: 'Fallas menores',
        notas: 'Puebla',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    },
    {
        id: 'HA-42647',
        marca: 'Isuzu',
        modelo: 'Elf 400',
        anio: 2012,
        tipo: 'pickup',
        origen: 'mexico',
        precioMercado: 220000,
        precioTotal: 81000,
        ahorroMXN: 139000,
        danio: 'Recuperado',
        notas: 'Quintana Roo',
        disponible: true,
        fechaLimite: '2026-03-05',
        foto: ''
    }
];
